type Usuario {
    _id: ID!
    nome: String
}
type Query {
    testes: [Usuario]
}
asçakçsljaoils;nhdnaklmsdlçjalsmd.masd/çla./s.d?:a}S.d,;.n alskjdmd,a.sd
a
sdas
d
alskjdmdsd
asçakçsljaoilsda
sdassda
s
