input incluirUsuario {
    nome: String
}
type Usuario {
    _id: ID!
    nome: String
}
type Query {
    obterUsuario(id: ID!): Usuario
    listarUsuarios: [Usuario]
}
type Mutation {
    criarUsuario(input: incluirUsuario): Usuario
}